# Generated by Django 6.1.1 on 2026-09-26 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooler_tag', models.CharField(db_index=True, help_text='Barcode value on the cooler tag.', max_length=50, unique=True)),
                ('serial_number', models.CharField(db_index=True, help_text='Barcode value on the serial number sticker.', max_length=50, unique=True)),
                ('asset_number', models.CharField(db_index=True, help_text='Asset number (usually typed manually).', max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Retired', 'Retired'), ('Lost', 'Lost')], default='Active', max_length=20)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['cooler_tag'],
            },
        ),
        migrations.CreateModel(
            name='ScanAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_tag', models.CharField(blank=True, max_length=50)),
                ('scanned_serial', models.CharField(blank=True, max_length=50)),
                ('scanned_asset', models.CharField(blank=True, max_length=50)),
                ('staff_id', models.CharField(db_index=True, max_length=100)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(choices=[('VERIFIED', 'Verified'), ('MISMATCH', 'Mismatch'), ('NOT_FOUND', 'Not Found'), ('PARTIAL', 'Partial Save'), ('DUPLICATE', 'Duplicate Same Day')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('mismatch_details', models.JSONField(blank=True, help_text='Which scanned field matched which unit (for mismatch review).', null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('unit', models.ForeignKey(blank=True, help_text='Matched unit, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='inventory.unit')),
            ],
            options={
                'verbose_name': 'Scan Attempt',
                'verbose_name_plural': 'Scan Attempts',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['staff_id', 'scanned_at'], name='inventory_s_staff_i_ec8b30_idx'), models.Index(fields=['result'], name='inventory_s_result_b4d390_idx')],
            },
        ),
    ]
